version: '2'
services:
  mongodb:
    image: mongo
    expose:
      - '27017'
  davis:
    build: .
    volumes:
      - .:/home/app/davis
      - /home/app/davis/node_modules
    ports:
      - "8080:3000"
    expose:
      - "8080"
    depends_on:
      - mongodb
    links:
      - mongodb:mongo
